title: jim
baseURL: https://the.jim.team/

languageCode: en-us
theme: hello-friend-ng

params:
  dateform: 2006-01-02

  homeSubtitle: happy valentines day! please, say yes. :)
  description: jim
  keywords: jim
